/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Committee, CommitteeInterface } from "../Committee";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldCommittee",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newCommittee",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "CommitteeSet",
    type: "event",
  },
  {
    inputs: [],
    name: "committee",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_committee",
        type: "address",
      },
    ],
    name: "setCommittee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Committee__factory {
  static readonly abi = _abi;
  static createInterface(): CommitteeInterface {
    return new utils.Interface(_abi) as CommitteeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Committee {
    return new Contract(address, _abi, signerOrProvider) as Committee;
  }
}
