/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKAP20Blacklist,
  IKAP20BlacklistInterface,
} from "../IKAP20Blacklist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "addBlacklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "revokeBlacklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKAP20Blacklist__factory {
  static readonly abi = _abi;
  static createInterface(): IKAP20BlacklistInterface {
    return new utils.Interface(_abi) as IKAP20BlacklistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKAP20Blacklist {
    return new Contract(address, _abi, signerOrProvider) as IKAP20Blacklist;
  }
}
