/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKAP20AdminApprove,
  IKAP20AdminApproveInterface,
} from "../IKAP20AdminApprove";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "adminApprove",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKAP20AdminApprove__factory {
  static readonly abi = _abi;
  static createInterface(): IKAP20AdminApproveInterface {
    return new utils.Interface(_abi) as IKAP20AdminApproveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKAP20AdminApprove {
    return new Contract(address, _abi, signerOrProvider) as IKAP20AdminApprove;
  }
}
