/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKYC, IKYCInterface } from "../IKYC";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "kycsLevel",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IKYC__factory {
  static readonly abi = _abi;
  static createInterface(): IKYCInterface {
    return new utils.Interface(_abi) as IKYCInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IKYC {
    return new Contract(address, _abi, signerOrProvider) as IKYC;
  }
}
