/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKYCBitkubChain,
  IKYCBitkubChainInterface,
} from "../IKYCBitkubChain";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "kycsLevel",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IKYCBitkubChain__factory {
  static readonly abi = _abi;
  static createInterface(): IKYCBitkubChainInterface {
    return new utils.Interface(_abi) as IKYCBitkubChainInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKYCBitkubChain {
    return new Contract(address, _abi, signerOrProvider) as IKYCBitkubChain;
  }
}
