/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INextTransferRouter,
  INextTransferRouterInterface,
} from "../INextTransferRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_project",
        type: "string",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INextTransferRouter__factory {
  static readonly abi = _abi;
  static createInterface(): INextTransferRouterInterface {
    return new utils.Interface(_abi) as INextTransferRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INextTransferRouter {
    return new Contract(address, _abi, signerOrProvider) as INextTransferRouter;
  }
}
